### ISSUE TITLE
Missing vendor in app/public 

### ISSUE THREAD

**Issue by eXXon48** [alexis-luna/codeigniter4-auth-and-user-management#1]
Looks like all js css files are missing  eg. 
/public/vendor/bootstrap/
/public/vendor/jquery/

**Comment by tambakdev** [comment]
> Looks like all js css files are missing eg.
> /public/vendor/bootstrap/
> /public/vendor/jquery/

 maybe put all assets requires into public directory/vendor

**Comment by alexisbriandev** [comment]
Hello @eXXon48,

Thanks for reporting. I fixed this issue with latest update.

Thanks for your idea too @uwaiscode
