### ISSUE TITLE
Invalid file: auth/auth/register.php 

### ISSUE THREAD

**Issue by SwapnilAkolkar** [alexis-luna/codeigniter4-auth-and-user-management#2]
When I click on Register link it shows this error.

**Comment by alexisbriandev** [comment]
Hello @SwapnilAkolkar

What is the error?

**Comment by treborin** [comment]
> When I click on Register link it shows this error.

Hi, did you solve this @SwapnilAkolkar ?
I get the same

**Comment by SwapnilAkolkar** [comment]
> > When I click on Register link it shows this error.
> 
> Hi, did you solve this @SwapnilAkolkar ?
> I get the same

Solved by relacing all the urls with including base_url and define that base_url in the settings .env file , I did first some trial and error , then  Ifound where exact the url pointed then I replace all urls with adding them with **$base_url**
